### ISSUE TITLE
Great to see the StockX PublicAPI & Question

### ISSUE THREAD

**Issue by heng2j** [stockx/PublicAPI#1]
Hi Team,

Congrats for pushing the PublicAPI for StockX. Currently I am working on a mobile prototyping sneaker app that use the data from the previous unofficial python StockX library. I am happy to see that There is a publicAPI pushed today. 

I have registered and requested for the developer account on the StockX Dev page, do you know when we can have API keys so we can use this API? And will there have any updates or affect to the python StockX library?

One more quick question, is it possible to get the historical sales data from the PublicAPI? And how's the permission of using the data from this API?

Thank you,
Heng

**Comment by Swampy821** [comment]
Hi Heng, 

Thanks for your interest in the public API! At the moment our Public API is in a beta state which we are testing with very specific power sellers. The Public API will be a long term project in StockX so I cannot give an accurate timeline of when it will be open to all users. 

At the moment I don't believe there is a way to pull all historical sales data and unfortunately I do not know the permission of using that yet either. We will definitely post any updates as they come. 

-Steve

**Comment by heng2j** [comment]
Hi Steve,

Thank you for the response. In this case, I am looking forward for the new updates. Appreciated.

Cheers,
Heng
